name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    outputs:
      should_run: ${{ steps.filter.outputs.workflows == 'true' || steps.filter.outputs.aqua == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check for relevant changes
        uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
            aqua:
              - '.aqua/**'

  check:
    name: Check
    needs: changes
    if: needs.changes.outputs.should_run == 'true'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install aqua
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        env:
          AQUA_CONFIG: ".aqua/aqua.yaml"
        with:
          aqua_version: "v2.57.0"

      - name: Run pinact
        run: pinact run --check

      - name: Run actionlint
        run: actionlint
