name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Setup Test
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      CI: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install chezmoi
        run: brew install chezmoi

      - name: Initialize chezmoi
        run: chezmoi init --apply -S .
        shell: zsh {0}
