name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Setup Test
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      CI: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install chezmoi
        run: brew install chezmoi

      - name: Initialize chezmoi
        run: chezmoi init --apply -S .
        shell: zsh {0}
